import { JobType, Periodicity, WorkSetup, Currency, Job } from "@/types/jobs";

export const jobs: Job[] = [
  {
    id: 1,
    title: "Software Engineer",
    description: "Develop and maintain scalable web applications.",
    salaryMin: 100000,
    salaryMax: 140000,
    author: "TechCorp",
    jobType: JobType.FullTime,
    location: "San Francisco",
    state: { name: "California", state_code: "CA" },
    workSetup: WorkSetup.Hybrid,
    periodicity: Periodicity.Year,
    currency: Currency.USD,
  },
  {
    id: 2,
    title: "Graphic Designer",
    description: "Create visual assets for web and print media.",
    salaryMin: 3500,
    salaryMax: 5500,
    author: "CreativeHub",
    jobType: JobType.Contractual,
    location: "Austin",
    state: { name: "Texas", state_code: "TX" },
    workSetup: WorkSetup.WorkFromHome,
    periodicity: Periodicity.Month,
    currency: Currency.USD,
  },
  {
    id: 3,
    title: "Data Analyst",
    description: "Analyze and visualize business data to drive decisions.",
    salaryMin: 80000,
    salaryMax: 100000,
    author: "Finlytics",
    jobType: JobType.FullTime,
    location: "New York City",
    state: { name: "New York", state_code: "NY" },
    workSetup: WorkSetup.OnSite,
    periodicity: Periodicity.Year,
    currency: Currency.USD,
  },
  {
    id: 4,
    title: "Marketing Specialist",
    description: "Plan and execute digital marketing campaigns.",
    salaryMin: 4500,
    salaryMax: 6500,
    author: "BrandMatrix",
    jobType: JobType.FullTime,
    location: "Chicago",
    state: { name: "Illinois", state_code: "IL" },
    workSetup: WorkSetup.Hybrid,
    periodicity: Periodicity.Month,
    currency: Currency.USD,
  },
  {
    id: 5,
    title: "Customer Support Representative",
    description: "Handle customer inquiries and resolve issues.",
    salaryMin: 3500,
    salaryMax: 4500,
    author: "Supportly",
    jobType: JobType.PartTime,
    location: "Orlando",
    state: { name: "Florida", state_code: "FL" },
    workSetup: WorkSetup.WorkFromHome,
    periodicity: Periodicity.Month,
    currency: Currency.USD,
  },
  {
    id: 6,
    title: "Project Manager",
    description: "Lead project teams and ensure timely delivery.",
    salaryMin: 90000,
    salaryMax: 120000,
    author: "BuildTech",
    jobType: JobType.FullTime,
    location: "Seattle",
    state: { name: "Washington", state_code: "WA" },
    workSetup: WorkSetup.Hybrid,
    periodicity: Periodicity.Year,
    currency: Currency.USD,
  },
  {
    id: 7,
    title: "UX/UI Designer",
    description: "Design user interfaces and improve user experiences.",
    salaryMin: 6000,
    salaryMax: 8000,
    author: "PixelWorks",
    jobType: JobType.Contractual,
    location: "Portland",
    state: { name: "Oregon", state_code: "OR" },
    workSetup: WorkSetup.WorkFromHome,
    periodicity: Periodicity.Month,
    currency: Currency.USD,
  },
  {
    id: 8,
    title: "Backend Developer",
    description: "Implement and optimize server-side logic and databases.",
    salaryMin: 95000,
    salaryMax: 130000,
    author: "DevStream",
    jobType: JobType.FullTime,
    location: "Denver",
    state: { name: "Colorado", state_code: "CO" },
    workSetup: WorkSetup.OnSite,
    periodicity: Periodicity.Year,
    currency: Currency.USD,
  },
  {
    id: 9,
    title: "Human Resources Coordinator",
    description: "Assist with HR processes, hiring, and employee relations.",
    salaryMin: 55000,
    salaryMax: 70000,
    author: "PeopleFirst",
    jobType: JobType.FullTime,
    location: "Raleigh",
    state: { name: "North Carolina", state_code: "NC" },
    workSetup: WorkSetup.Hybrid,
    periodicity: Periodicity.Year,
    currency: Currency.USD,
  },
  {
    id: 10,
    title: "QA Engineer",
    description: "Test and ensure product quality through manual and automated testing.",
    salaryMin: 80000,
    salaryMax: 110000,
    author: "QualityMatters",
    jobType: JobType.FullTime,
    location: "Salt Lake City",
    state: { name: "Utah", state_code: "UT" },
    workSetup: WorkSetup.Hybrid,
    periodicity: Periodicity.Year,
    currency: Currency.USD,
  },
  {
    id: 11,
    title: "Mobile App Developer",
    description: "Build cross-platform mobile applications.",
    salaryMin: 90000,
    salaryMax: 130000,
    author: "AppNest",
    jobType: JobType.FullTime,
    location: "Atlanta",
    state: { name: "Georgia", state_code: "GA" },
    workSetup: WorkSetup.WorkFromHome,
    periodicity: Periodicity.Year,
    currency: Currency.USD,
  },
  {
    id: 12,
    title: "Technical Writer",
    description: "Create and maintain technical documentation.",
    salaryMin: 4500,
    salaryMax: 6500,
    author: "DocuStream",
    jobType: JobType.Contractual,
    location: "Phoenix",
    state: { name: "Arizona", state_code: "AZ" },
    workSetup: WorkSetup.WorkFromHome,
    periodicity: Periodicity.Month,
    currency: Currency.USD,
  },
  {
    id: 13,
    title: "Cybersecurity Analyst",
    description: "Monitor and secure network and data systems.",
    salaryMin: 100000,
    salaryMax: 140000,
    author: "SecureEdge",
    jobType: JobType.FullTime,
    location: "Boston",
    state: { name: "Massachusetts", state_code: "MA" },
    workSetup: WorkSetup.Hybrid,
    periodicity: Periodicity.Year,
    currency: Currency.USD,
  },
  {
    id: 14,
    title: "Business Analyst",
    description: "Analyze business requirements and processes for improvement.",
    salaryMin: 80000,
    salaryMax: 110000,
    author: "InsightCorp",
    jobType: JobType.FullTime,
    location: "Indianapolis",
    state: { name: "Indiana", state_code: "IN" },
    workSetup: WorkSetup.OnSite,
    periodicity: Periodicity.Year,
    currency: Currency.USD,
  },
  {
    id: 15,
    title: "DevOps Engineer",
    description: "Maintain CI/CD pipelines and automate infrastructure.",
    salaryMin: 110000,
    salaryMax: 150000,
    author: "CloudCore",
    jobType: JobType.FullTime,
    location: "San Diego",
    state: { name: "California", state_code: "CA" },
    workSetup: WorkSetup.Hybrid,
    periodicity: Periodicity.Year,
    currency: Currency.USD,
  },
];
